### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by endel** [sindresorhus/negative-zero#1]

**Comment by sindresorhus** [comment]
It's all in the linked Wikipedia article.

**Comment by endel** [comment]
I see. Thanks for the explanation. IMHO it's kinda weird to have a package with a single-line function.

**Comment by kevva** [comment]
Easier than having to remember it in your head.

**Comment by sindresorhus** [comment]
@endel The alternative is remembering how this work, which is insane as the check makes no sense when looking at it without having read the ECMAScript spec carefully. Copy pasting is an alternative, but that's not very DRY and will require you to include a comment anyways on what it does. Think of it as lego blocks. We make ready made blocks so you and other don't have to care about how it works internally and what it's supposed to do. I know this is a big shift in thinking for many coming from the front-end or other languages, but try it out, it's absolutely amazing.
