### ISSUE TITLE
why is the zero check necessary?

### ISSUE THREAD

**Issue by spelunk** [sindresorhus/negative-zero#3]
I can't find a freely available copy of IEEE 754 but why is the zero check necessary?  AFAICT the reciprocal for a number that isn't `-0` is never `-Infinity` even for denormal numbers and the machine Epsilon `Number.EPSILON`

**Comment by sindresorhus** [comment]
I don't remember exactly. It's not strictly needed. I probably added it for readability reasons or as a shortcut so it wouldn't try to divide if not a zero. Doesn't really matter though, as the correct solution today would be `Object.is(input, -0)`.
